---
#Need Change
resources:
    s1:
        hostname: s1.gd2h-bdmd.com
        ip: 192.168.103.41
    s2:
        hostname: s2.gd2h-bdmd.com
        ip: 192.168.103.42
    s3:
        hostname: s3.gd2h-bdmd.com
        ip: 192.168.103.43
    s4:
        hostname: s4.gd2h-bdmd.com
        ip: 192.168.103.44
    s5:
        hostname: s5.gd2h-bdmd.com
        ip: 192.168.103.45
#Need Change
domain: gd2h-bdmd.com
#Need Change
modules:
    testmodule:
        manual_only: True
    debian-repo:
        priority: 0
    pypi:
        priority: 0
        offline:
            web_dir: "/var/www/pypi"
            server: s1
            port: 20004
    ssh-root-key:
        priority: 1
    basic:
        priority: 1
    dns-server:
        priority: 1
        #Need Change
        resources:
            - s1
        #Need Change
        subnet: 192.168.103.0/24
        #May need to delete
        #zones:
        #    - name: bdmd.com
        #      type: forward
        #      forwarders: "{192.168.50.2;}"
        options:
            directory: "\"/var/cache/bind\""
            #Need Change
            forwarders: "{223.5.5.5;223.6.6.6;}"
            dnssec-validation: no
            auth-nxdomain: on
            #Need Change
            allow-query: "{localhost;localnets;192.168.103.0/24;}"
    vbox:
        resources:
            - s1
    etcd:
        require: 
            - dns-server
        resources:
            - s1
            - s2
            - s3
        #Need Change
        cluster: 'gd2h'
        datadir: '/var/lib/etcd'
        logdir: '/var/log/etcd'
    flannel:
        require:
            - etcd
        network: '10.100.0.0/16'
        logdir: '/var/log/flannel'
    docker:
        require:
            - flannel
            - nfs
        images:
          - /data/docker/ambari-image.tar
          - /data/docker/elasticsearch.tar
          - /data/docker/mongodb.tar
          - /data/docker/overall.tar
          - /data/docker/redis.tar
    cxoracle:
        #Need Change
        manual_only: True
        resources:
            - s1
        java_home: /usr/jdk64/jdk1.8.0_60
        jdk_tar_path: /data/vmshare/software/jdk-8u60-linux-x64.tar.gz
        instant_client_sdk: /data/vmshare/software/instantclient-sdk-linux-x86-64-11.2.0.2.0.zip
        instant_client_basic: /data/vmshare/software//instantclient-basic-linux-x86-64-11.2.0.2.0.zip
    nfs:
        server: s1
    html2pdf:
    ca:
