---
#Need Change
resources:
    s1:
        hostname: s1.njwjw-bdmd.com
        ip: 10.40.49.61
    s2:
        hostname: s2.njwjw-bdmd.com
        ip: 10.40.49.62
    s3:
        hostname: s3.njwjw-bdmd.com
        ip: 10.40.49.63
    s4:
        hostname: s4.njwjw-bdmd.com
        ip: 10.40.49.64
#Need Change
domain: njwjw-bdmd.com
#Need Change
modules:
    cbasic:
        yum:
            use_aliyun_repo: true
        pip:
            index: "http://mirrors.aliyun.com/pypi/simple/"
            trusted_host: mirrors.aliyun.com
        ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnko3/WSc0HXB80m8ZkTmXBc+MjB4TaZZvapYPMMvs4MYtTpJhlxqjNAO5zYIx9oyLXmCMuE60iZaI00QnXEuGEaJfrFYr/lpApOnOEiBP/GyG89hTjwKnEFyn9Qze0MsMcBGu4BN4VwIic5aXiZwHQ5heM8Tu2jjJi6Opbcmp3YtuED4lwnYBDlf8etiW2EwNfaDH2y3f/X/rtKRJ7eMWCL0oDe7iF1oTUQDhiSND3jcfyPvoK597sbEz0ne15D3UygPSyFvtMO+8gDJwzdduIUCa6iSM18igxDpEoWJmBl2cst2x/b2KADjF9YHkHNoKmHRrfynfhmqXiMOiwurl root@s1"
    openvpn:
        server_ip: tun.iyoudoctor.com
        server_port: 10190
        clients:
            - name: s1
              cert: /Users/f/hospital/njwjw/vpn0.njwjw-bdmd.com.cert.pem
              key: /Users/f/hospital/njwjw/vpn0.njwjw-bdmd.com.key.pem
    dns:
        resources:
            - s1
        subnet: 10.40.49.0/24
        records:
            - ip: 10.40.49.12
              hostname: kubeapi
