---
#Need Change
resources:
    s1:
        hostname: k8s0.dev-bdmd.com
        ip: 192.168.100.17
    s2:
        hostname: k8s1.dev-bdmd.com
        ip: 192.168.100.18
    s3:
        hostname: k8s2.dev-bdmd.com
        ip: 192.168.100.22
    s4:
        hostname: k8s3.dev-bdmd.com
        ip: 192.168.100.23
    s5:
        hostname: k8s4.dev-bdmd.com
        ip: 192.168.100.24
#Need Change
domain: dev-bdmd.com
#Need Change
modules:
    cbasic:
        allow_partial_deploy: true
        http_proxy: http://192.168.100.41:3128
        yum:
            use_proxy: true
            use_aliyun_repo: true
        pip:
            index: "http://mirrors.aliyun.com/pypi/simple/"
            trusted_host: mirrors.aliyun.com
            use_proxy: true
        ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnko3/WSc0HXB80m8ZkTmXBc+MjB4TaZZvapYPMMvs4MYtTpJhlxqjNAO5zYIx9oyLXmCMuE60iZaI00QnXEuGEaJfrFYr/lpApOnOEiBP/GyG89hTjwKnEFyn9Qze0MsMcBGu4BN4VwIic5aXiZwHQ5heM8Tu2jjJi6Opbcmp3YtuED4lwnYBDlf8etiW2EwNfaDH2y3f/X/rtKRJ7eMWCL0oDe7iF1oTUQDhiSND3jcfyPvoK597sbEz0ne15D3UygPSyFvtMO+8gDJwzdduIUCa6iSM18igxDpEoWJmBl2cst2x/b2KADjF9YHkHNoKmHRrfynfhmqXiMOiwurl root@s1"
