---
#Need Change
resources:
    s1:
        hostname: s1.wjwkys-bdmd.com
        ip: 191.168.101.188
    s2:
        hostname: s2.wjwkys-bdmd.com
        ip: 191.168.101.130
    s3:
        hostname: s3.wjwkys-bdmd.com
        ip: 191.168.101.131
    s4:
        hostname: s4.wjwkys-bdmd.com
        ip: 191.168.101.132
    s5:
        hostname: s5.wjwkys-bdmd.com
        ip: 191.168.101.133
#Need Change
domain: wjwkys-bdmd.com
#Need Change
modules:
    cbasic:
        yum:
            use_aliyun_repo: true
        pip:
            index: "http://mirrors.aliyun.com/pypi/simple/"
            trusted_host: mirrors.aliyun.com
        ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnko3/WSc0HXB80m8ZkTmXBc+MjB4TaZZvapYPMMvs4MYtTpJhlxqjNAO5zYIx9oyLXmCMuE60iZaI00QnXEuGEaJfrFYr/lpApOnOEiBP/GyG89hTjwKnEFyn9Qze0MsMcBGu4BN4VwIic5aXiZwHQ5heM8Tu2jjJi6Opbcmp3YtuED4lwnYBDlf8etiW2EwNfaDH2y3f/X/rtKRJ7eMWCL0oDe7iF1oTUQDhiSND3jcfyPvoK597sbEz0ne15D3UygPSyFvtMO+8gDJwzdduIUCa6iSM18igxDpEoWJmBl2cst2x/b2KADjF9YHkHNoKmHRrfynfhmqXiMOiwurl root@s1"
    openvpn:
        server_ip: tun.iyoudoctor.com
        server_port: 10190
        clients:
            - name: s1
              cert: /Users/f/hospital/wjwkys/vpn0.wjwkys-bdmd.com.cert.pem
              key: /Users/f/hospital/wjwkys/vpn0.wjwkys-bdmd.com.key.pem
    dns:
        resources:
            - s1
        subnet: 191.168.101.188/24
        records:
            - ip: 191.168.101.188
              hostname: kubeapi
